# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "currency_convert": "01_utils.ipynb"}

modules = ["core.py",
           "utils.py"]

doc_url = "https://ricklamers.github.io/probable_sniffle_nbdev/"

git_url = "https://github.com/ricklamers/probable_sniffle_nbdev/tree/master/"

def custom_doc_links(name): return None
